# Generated by Django 3.2.2 on 2021-05-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_time',
            new_name='pub_date',
        ),
    ]
